name: The_Best_Plugin
main: com.alejandro.thebestplugin.TheBestPlugin
version: '1.1'

commands:
  register-account:
    description: Link this user's Discord and Minecraft accounts.
    usage: /register-account <discord_id> <minecraft_uuid>
    permission: op
    permission-message: You can't use this. Ask an operator to register an account.
  launch:
    description: something
    usage: N word
    permission: op